### ISSUE TITLE
Models either don't appear or crash the program

### ISSUE THREAD

**Issue by RagdollClash** [KillzXGaming/Smash-Forge#10]
With the latest version, it appears that now every model I load into it, no matter what console it's for, it will either not display the model or just straight up crash the program.
![2018-07-28_11-10-38](https://user-images.githubusercontent.com/15317421/43359406-dd458cf0-9256-11e8-8094-16fd24d36eb8.png)
![2018-07-28_11-12-00](https://user-images.githubusercontent.com/15317421/43359416-0e1f4208-9257-11e8-8ee6-f26527891b90.png)
This is on the latest commit, a39049a9d440dd1755c585c62f3b9591fc5093ca.

**Comment by RagdollClash** [comment]
Testing each commit starting from v0.3-Alpha:
152172477bac941ede31520a287c04fba01347e1
Works as expected
![2018-07-28_11-25-22](https://user-images.githubusercontent.com/15317421/43359559-f433634a-9258-11e8-815f-eb96f07d9e27.png)

745e83540aaa3aafa21076300b6cf451508aadb9
Models appear black when being loaded, you can make it display textures by changing the debug shader.
![2018-07-28_11-22-55](https://user-images.githubusercontent.com/15317421/43359550-c7fa71e2-9258-11e8-8691-ceb70fd6529e.png)

01f8884a7e1c7d50b9f216c95dff0ca55f841c91
Model no longer displays no matter what you do
![2018-07-28_11-26-42](https://user-images.githubusercontent.com/15317421/43359568-24573ff6-9259-11e8-8222-223754efdb4c.png)

**Comment by KillzXGaming** [comment]
Try the latest one, should open correctly now.

**Comment by RagdollClash** [comment]
Tested the latest build on the releases page, the model still doesn't seem to appear.
![2018-07-28_12-38-14](https://user-images.githubusercontent.com/15317421/43360039-193edbf6-9263-11e8-8f5f-9c44db8417b3.png)
If it helps at all, my GPU is a GTX 1060.

**Comment by KillzXGaming** [comment]
Can you do file - export shader error logs and send the BFRES one over? Should save to the folder forge is in.

**Comment by RagdollClash** [comment]
[BFRES_ErrorLog.txt](https://github.com/KillzXGaming/Smash-Forge/files/2238303/BFRES_ErrorLog.txt)

**Comment by KillzXGaming** [comment]
Alright try it again and see if it works.

**Comment by RagdollClash** [comment]
The model still doesn't appear to be showing up.
[BFRES_ErrorLog.txt](https://github.com/KillzXGaming/Smash-Forge/files/2238338/BFRES_ErrorLog.txt)

**Comment by KillzXGaming** [comment]
Odd. Try replacing the shader with this one in lib\shader, 

[BFRES_vs.txt](https://github.com/KillzXGaming/Smash-Forge/files/2238359/BFRES_vs.txt)

**Comment by RagdollClash** [comment]
Model appears now, although Marina's right arm is messed up.
![2018-07-28_17-17-07](https://user-images.githubusercontent.com/15317421/43361670-0fa3d9ee-928a-11e8-9b57-bde667114da1.png)

I loaded up Pearl's model and her textures aren't changing from Marina's textures.
![2018-07-28_17-20-03](https://user-images.githubusercontent.com/15317421/43361686-cc909696-928a-11e8-8853-ac50e4fc4eaf.png)

**Comment by ScanMountGoat** [comment]
If the shader doesn't compile and you try to render with it, the application will crash.

**Comment by RagdollClash** [comment]
Using latest master from https://github.com/jam1garner/Smash-Forge, having the same issue there.
![2018-08-06_13-05-56](https://user-images.githubusercontent.com/15317421/43738431-77162f46-9979-11e8-844e-d81ddfa83aea.png)
[BFRES Error Log.txt](https://github.com/KillzXGaming/Smash-Forge/files/2263928/BFRES.Error.Log.txt)
[Point Error Log.txt](https://github.com/KillzXGaming/Smash-Forge/files/2263929/Point.Error.Log.txt)

**Comment by ScanMountGoat** [comment]
Report issues on the main repo now. All of the bfres changes have been merged into master.

**Comment by RagdollClash** [comment]
https://github.com/jam1garner/Smash-Forge/issues/238
