### ISSUE TITLE
Models duplicated in rotated position

### ISSUE THREAD

**Issue by Makiah** [KillzXGaming/Smash-Forge#14]
In Smash Forge: 
![image](https://user-images.githubusercontent.com/10727824/43724123-18c27bdc-994e-11e8-8a66-45d7a75116a8.png)

In Maya 2016 (upon importing the DAE): 
![image](https://user-images.githubusercontent.com/10727824/43724041-f430a460-994d-11e8-8230-eb0d85a8c3a0.png)

This happens right as models are imported in Smash Forge.  Animations only play on one model, the model laying sideways remains motionless but is moved along with the mobile model.  I'll see whether I can figure out the root cause.

**Comment by KillzXGaming** [comment]
Dae exporting from forge doesn't work correctly atm. The weights sometimes work and sometimes don't.

**Comment by Makiah** [comment]
Oh ok, the reason that the two models show up for the Bass is because Forge automatically imports every model in a given bfres.  Is this its intended functionality?  For example, in this case, "Bass" and "Bass_Boneless" are imported, but shouldn't users be prompted for the one they wish to import?  I could probably make a quick dialog to ask users which one they'd like to open.

**Comment by KillzXGaming** [comment]
I intend on having a configuration box for dae export settings including which models to export and some other options. The export feature just isn't fully finished yet so it has issues like bones in the wrong place and weights not applying.
