### ISSUE TITLE
Trouble exporting .dae for a splatoon 2 map

### ISSUE THREAD

**Issue by ethanl21** [KillzXGaming/Smash-Forge#5]
When trying to export the .dae for New Albacore Hotel from splatoon 2, Smash forge creates a bunch of textures in the specified folder and is then labeled as "Not Responding" by Windows. No .dae is outputted. Is there a possible fix for this?

Using latest smash forge compiled in visual studio.

Running in Windows 10 using an i5 6600k and a GTX 1070.

**Comment by KillzXGaming** [comment]
Dae exporting/importing is a bit broken atm but I'll go back to fix that soon.

**Comment by ethanl21** [comment]
Thank you for the response. I figured out that the "Not Responding" thing is caused by the program taking a long time to process or something, so that in itself doesn't seem to bad. (Smaller maps export just fine) The resulting dae is still broken, however. Thanks!
